# Generated by Django 4.2.4 on 2023-08-23 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stok', models.IntegerField(default=20)),
                ('discount_until', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
