# Generated by Django 4.2.4 on 2023-08-24 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripción', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField()),
                ('priority', models.IntegerField(default=3)),
            ],
        ),
    ]
