# Generated by Django 4.2.4 on 2023-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='signature',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
