# Generated by Django 4.2.4 on 2023-08-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='adress',
            new_name='addres',
        ),
    ]
